apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  labels:
    app: nexus-bot
type: Opaque
data:
  # Substitua pelo valor da sua chave Groq em base64 (ex: echo -n "gsk_..." | base64)
  GROQ_API_KEY: aW5zaXJhX3N1YV9jaGF2ZV9hcXVp